Diego Seisdedos Stoz
BARB27 - Equipe 11.74

Le code fonctionne dans sa globalité. 

Cependant : 
    - Je n'ai pas été capable de garder le fichier ouvert après file <name> et je suis donc obligé de 
    demander (pour les commandes qui nécéssite le fichier) à nouveau le nom du fichier en plus de la commande.
    - Je n'ai pas réussi à généraliser pour sum et avg à un nombre n, mon programme se limite à 2 nombre.
    - Je n'arrive pas à lever des erreurs aux cas par cas, lorsque je fais raise CommandError (" ") (par exemple) et 
    qu'ensuite dans je fais except CommandError, python me dit que CommandError n'est pas défini. 
    - J'ai pas fais de fichiers test par manque de temps.